package fjab.loancalc.view;

public enum FormElement {
	ANNUAL_INTEREST_RATE,LOAN_AMOUNT,REPAYMENT_PERIODICITY,LOAN_LENGTH,LOAN_LENGTH_YEARS,LOAN_LENGTH_MONTHS,
	OK_BUTTON,TABLE,AMORTIZATION_TABLE;
}
